[functions]
  node_bundler = "esbuild"

# Allow API routes to work
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# (Optional) block direct access to function files
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/403.html"
  status = 403
  force = true

[[redirects]]
  from = "/netlify/functions/*"
  to = "/403.html"
  status = 403
  force = true

[[redirects]]
  from = "/netlify/*"
  to = "/403.html"
  status = 403
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; script-src-attr 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://i.ibb.co; font-src 'self' https://fonts.gstatic.com; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; frame-src 'none'; form-action 'self'; upgrade-insecure-requests"
