[functions]
  node_bundler = "esbuild"

# Allow API routes to work
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# (Optional) block direct access to function files
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/403.html"
  status = 403
